### ISSUE TITLE
Package fails with Hapi 15.

### ISSUE THREAD

**Issue by totherik** [krakenjs/swaggerize-hapi#63]
Just tried using the current latest version of Hapi (15.2.0) and server startup failed with the following error.

``` bash
TypeError: child.schema._getLabel is not a function
    at _base (/fakeproject/node_modules/hapi/node_modules/joi/lib/object.js:157:93)
    at _validate (/fakeproject/node_modules/hapi/node_modules/joi/lib/any.js:540:37)
    at _validateWithOptions (/fakeproject/node_modules/hapi/node_modules/joi/lib/any.js:600:29)
    at root.validate (/fakeproject/node_modules/hapi/node_modules/joi/lib/index.js:105:23)
    at Object.internals.input (/fakeproject/node_modules/hapi/lib/validation.js:137:20)
    at exports.query (/fakeproject/node_modules/hapi/lib/validation.js:30:22)
    at each (/fakeproject/node_modules/hapi/lib/request.js:380:16)
    at iterate (/fakeproject/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/fakeproject/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at internals.Auth._authenticate (/fakeproject/node_modules/hapi/lib/auth.js:222:16)
    at internals.Auth.authenticate (/fakeproject/node_modules/hapi/lib/auth.js:197:17)
    at each (/fakeproject/node_modules/hapi/lib/request.js:380:16)
    at iterate (/fakeproject/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/fakeproject/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at internals.state (/fakeproject/node_modules/hapi/lib/route.js:362:16)
    at each (/fakeproject/node_modules/hapi/lib/request.js:380:16)
```

**Comment by tlivings** [comment]
Addressed via https://github.com/tlivings/enjoi/commit/852ee93a72394df94fa2cabcaa199d17da245476

**Comment by tlivings** [comment]
Reopened since this requires major version bumps.

**Comment by dcharbonnier** [comment]
any fox coming soon for this ?

**Comment by jasonmacdonald** [comment]
I'm getting the following error with Hapi 15

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'register' of undefined

**Comment by Cybolic** [comment]
Is there a temporary solution for this? I've tried updating joi and enjoi to their latest versions to no avail.

**Comment by tlivings** [comment]
Yes - we still need to straighten out the dependencies and publish to support the breaking changes.

**Comment by vobujs** [comment]
+1 for @Cybolic 's shrinkwrap fix, works for me too

**Comment by rodoabad** [comment]
Those are the only two that I need to change in my shrinkwrap?

**Comment by dcharbonnier** [comment]
this is really annoying, need help ?

**Comment by Cybolic** [comment]
@dcharbonnier, I started trying to clean up the dependencies in my fork (https://github.com/Cybolic/swaggerize-hapi). It has some non-reported bug fixes and is a few commits behind by now since I haven't been using swaggerize-hapi for a while, but it might be useful to you anyway as a starting point.

**Comment by stickyhands** [comment]
👍

**Comment by antonioasmoura** [comment]
News guys ? :(

**Comment by antonioasmoura** [comment]
I thinks this solve. https://github.com/krakenjs/swaggerize-routes/compare/master...Kitanotori:jwt-authorization-support

**Comment by tlivings** [comment]
New major version out.
