### ISSUE TITLE
formData validation for type 'file'

### ISSUE THREAD

**Issue by fabidona** [krakenjs/swaggerize-hapi#68]
hi!

I can't validate a request with a formData parameter of type 'file'. I use the follow yaml file for the request configuration:

```
[...]
paths:
  '/content':
    post:
      description: insert new content
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          type: file
          in: formData
          description: content stream
          required: true
        - name: filename
          type: string
          in: formData
          description: the file name
          required: true
      responses:
        '201':
          description: Insert ok
          headers:
             location:
               type: string
          schema:
              $ref: ../models/content-post-response.yaml
        default:
          description: An error occurred
          schema:
            $ref: ../models/errors.yaml
```

When i perform the request and I post a file the validation process fails comparing a object (the value is a Uint8Array) against a string for the 'file' parameter and swagger get out the response to hapi with errors 

`child "file" fails because ["value" must be a string] `

Response:

```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "child \"file\" fails because [\"value\" must be a string]",
  "validation": {
    "source": "payload",
    "keys": [
      "file"
    ]
  }
}

```
Is the right manner to upload a file or maybe some bugs on validation process with file and formdata ?

thanks all for advice!

**Comment by subeeshcbabu** [comment]
Because there is no primitive data type `file` for json schema or joi schema, the enjoi/joi based validator added the `file` type support by defining the type of the data to be `string`. The validator has no built-in coercion from object to string when it comes to `file` type.

**Comment by alexb-uk** [comment]
Hi,

I'm also facing this same error message but can't see the best/any solution.

I've spent a good hour reading various threads / discussions on this but I'm still very confused.

Please could someone point me in the direction of the best practice to resolve this?

For example:

- Is it best to skip swaggerize-hapi entirely for the moment: https://stackoverflow.com/questions/42147896/upload-file-with-swaggerize-hapi-and-node-js
- Or is it possible to create a global plugin to stream the file upload prior to the validator running?
- Or is it best to switch from "multipart/form-data" to "application/x-www-form-urlencoded" like the Petstore /upload example: https://github.com/krakenjs/swaggerize-hapi/blob/master/test/test-swaggerize-hapi.js
- Or has this actually been fixed and the error I'm seeing is a problem on my side, e.g. config or wiring?

```javascript
{ Error: child "importFile" fails because ["value" must be a string]
    at postValidate (C:\Users\alexb\PhpstormProjects\listings-api\node_modules\hapi\lib\validation.js:85:48)
    at Hoek.once (C:\Users\alexb\PhpstormProjects\listings-api\node_modules\hapi\lib\protect.js:50:16)
    at wrapped (C:\Users\alexb\PhpstormProjects\listings-api\node_modules\hoek\lib\index.js:875:20)
    at C:\Users\alexb\PhpstormProjects\listings-api\node_modules\swaggerize-hapi\lib\index.js:115:29
    at C:\Users\alexb\PhpstormProjects\listings-api\node_modules\async\lib\async.js:726:13
    at C:\Users\alexb\PhpstormProjects\listings-api\node_modules\async\lib\async.js:52:16
    at C:\Users\alexb\PhpstormProjects\listings-api\node_modules\async\lib\async.js:264:21
    at C:\Users\alexb\PhpstormProjects\listings-api\node_modules\async\lib\async.js:44:16
    at C:\Users\alexb\PhpstormProjects\listings-api\node_modules\async\lib\async.js:723:17
    at C:\Users\alexb\PhpstormProjects\listings-api\node_modules\async\lib\async.js:167:37
    at C:\Users\alexb\PhpstormProjects\listings-api\node_modules\swaggerize-routes\lib\validator.js:133:29
    at internals.Any.validate (C:\Users\alexb\PhpstormProjects\listings-api\node_modules\enjoi\node_modules\joi\lib\any.js:670:16)
    at Object.validateParameter [as validate] (C:\Users\alexb\PhpstormProjects\listings-api\node_modules\swaggerize-routes\lib\validator.js:123:28)
    at Object.formValidators.(anonymous function) [as importFile] (C:\Users\alexb\PhpstormProjects\listings-api\node_modules\swaggerize-hapi\lib\index.js:98:43)
    at C:\Users\alexb\PhpstormProjects\listings-api\node_modules\swaggerize-hapi\lib\index.js:112:50
    at C:\Users\alexb\PhpstormProjects\listings-api\node_modules\async\lib\async.js:718:13
    at Immediate.iterate (C:\Users\alexb\PhpstormProjects\listings-api\node_modules\async\lib\async.js:262:13)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  data:
   { ValidationError: child "importFile" fails because ["value" must be a string]
       at Object.exports.process (C:\Users\alexb\PhpstormProjects\listings-api\node_modules\enjoi\node_modules\joi\lib\errors.js:140:17)
       at internals.Any.validate (C:\Users\alexb\PhpstormProjects\listings-api\node_modules\enjoi\node_modules\joi\lib\any.js:667:25)
       at Object.validateParameter [as validate] (C:\Users\alexb\PhpstormProjects\listings-api\node_modules\swaggerize-routes\lib\validator.js:123:28)
       at Object.formValidators.(anonymous function) [as importFile] (C:\Users\alexb\PhpstormProjects\listings-api\node_modules\swaggerize-hapi\lib\index.js:98:43)
       at C:\Users\alexb\PhpstormProjects\listings-api\node_modules\swaggerize-hapi\lib\index.js:112:50
       at C:\Users\alexb\PhpstormProjects\listings-api\node_modules\async\lib\async.js:718:13
       at Immediate.iterate (C:\Users\alexb\PhpstormProjects\listings-api\node_modules\async\lib\async.js:262:13)
       at runCallback (timers.js:672:20)
       at tryOnImmediate (timers.js:645:5)
       at processImmediate [as _immediateCallback] (timers.js:617:5)
     name: 'ValidationError',
     details: [ [Object] ],
     _object:
      { value: <Buffer 50 4b 03 04 14 00 08 08 08 00 72 6e 35 4b 00 00 00 00 00 00 00 00 00 00 00 00 11 00 00 00 64 6f 63 50 72 6f 70 73 2f 63 6f 72 65 2e 78 6d 6c ef bf bd ... >,
        consumes: [Object],
        in: 'formData' },
     annotate: [Function] },
  isBoom: true,
  isServer: false,
  output:
   { statusCode: 400,
     payload:
      { statusCode: 400,
        error: 'Bad Request',
        message: 'child "importFile" fails because ["value" must be a string]',
        validation: [Object] },
     headers: {} },
  reformat: [Function],
  typeof: [Function] }
```

Swagger snippet:
```javascript
/imports:
 post:
  consumes:
	- multipart/form-data
  produces: 
	- application/hal+json
  parameters:
	- in: formData
	  name: importFile
	  type: file
	  description: The file to import.
	  required: true
	- in: formData
	  name: format
	  type: string
	  required: false
```

Many thanks for any help or advice.

Alex

**Comment by alexb-uk** [comment]
Ok I think I'm understanding a little more..... 

The issue is the contents of the file being uploaded. In my first test I was using an .xlsx file which is encoded in binary (or some odd MS format at least. If I test with a standard text file my code works perfectly.

So to revise my question is the best solution for me to create a HAPI plugin that can convert XLSX to some decoded format prior to it hitting the JOI validator?

Thanks

**Comment by alexb-uk** [comment]
Just in case anyone else comes across this issue a workaround for is to create HAPI plugin that moves the file upload data away from where the JOI validator will see it. 

Quite a hack but couldn't figure out any other solution. For example this will fire for every request for every operation 👎 :

```javascript
exports.register = (server, options, next) => {
  server.ext('onPostAuth', (request, reply) => {  
    // Work around for binary file parsing issue: https://github.com/krakenjs/swaggerize-hapi/issues/68
    if (request.payload) {
      if (request.payload.importFile) {
        request.file = request.payload.importFile;
        delete request.payload.importFile;
      }
    }

    return reply.continue();
  });

  next();
};
```
But you can still leave the parameter as required in swagger
```javascript
"parameters": [
  {
	"in": "formData",
	"name": "importFile",
	"type": "file",
	"description": "The file to import.",
	"required": true
  },
```

**Comment by tlivings** [comment]
I am reopening so I can test and fix against latest.

**Comment by tlivings** [comment]
This should be addresses now that it is being validated as binary (string or buffer) and returning the buffer to the payload for parsing however you like in the handler.

Note: doesn't support streams.
