### ISSUE TITLE
YAML as api SyntaxError: Invalid regular expression: missing /

### ISSUE THREAD

**Issue by Cheprer** [krakenjs/swaggerize-hapi#76]
Hi there,

I'm having an issue with loading my YAML document. Can you help me out here please?

Code:
```javascript
    {
      plugin: swaggerize,
      options: {
        api: require('./swagger_v2.yaml'),
      },
    },
```

Error:
```javascript
swagger_v2.yaml:9
basePath: /v2.1
          ^
SyntaxError: Invalid regular expression: missing /
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```
And when I put apostrophe around basePath: 'v2.1' it continues:

```javascript
swagger_v2.yaml:14
  /user:
  ^
SyntaxError: Invalid regular expression: missing /
```

**Comment by antonioasmoura** [comment]
Did you solved?

**Comment by Cheprer** [comment]
Hi @antonioasmoura, I've used hapi-swagger at the end. Not sure if someone fixed it.

**Comment by tlivings** [comment]
shouldn't be an issue.
