### ISSUE TITLE
x- custom properties are not allowed at top level

### ISSUE THREAD

**Issue by jdarling** [krakenjs/swaggerize-hapi#79]
Currently if you try and add x- custom properties at the top level of the document (totally valid according to the OpenAPI specification and works with other generators) you get an error when trying to load the API via the options.

```
ValidationError: "x-constants" is not allowed
    at Object.exports.process (/home/jdarling/uapi/server/node_modules/enjoi/node_modules/joi/lib/errors.js:140:17)
    at internals.Any.validate (/home/jdarling/uapi/server/node_modules/enjoi/node_modules/joi/lib/any.js:667:25)
    at swaggerize (/home/jdarling/uapi/server/node_modules/swaggerize-routes/lib/index.js:55:35)
    at Object.register (/home/jdarling/uapi/server/node_modules/swaggerize-hapi/lib/index.js:33:18)
    at Object.target [as register] (/home/jdarling/uapi/server/node_modules/joi/lib/types/object/index.js:77:34)
    at each (/home/jdarling/uapi/server/node_modules/hapi/lib/plugin.js:310:14)
    at iterate (/home/jdarling/uapi/server/node_modules/items/lib/index.js:36:13)
    at done (/home/jdarling/uapi/server/node_modules/items/lib/index.js:28:25)
    at Object.exports.register (/home/jdarling/uapi/server/node_modules/vision/lib/index.js:57:12)
    at Object.target [as register] (/home/jdarling/uapi/server/node_modules/joi/lib/types/object/index.js:77:34)
```

I've worked around this by first loading the schema by hand and then removing the top level x- definitions using the following:

```
const removeTopLevelX = (schema)=>{
  const reIsX = /^x-/;
  return Object.keys(schema).reduce((s, key)=>{
    if(reIsX.exec(key)){
      return s;
    }
    s[key] = schema[key];
    return s;
  }, {});
};
```

Then registering as:

```
  server.register([
      Inert,
      Vision,
      {
          register: Swaggerize,
          options: {
              api: removeTopLevelX(schema),
              handlers
          }
      }
    ], (err) => {
```

IMHO this shouldn't be necessary and really it means that you have to pass around the "real schema" instead of referencing it in code.

**Comment by tlivings** [comment]
Schema validation is based on the swagger schema. Not sure why this would be failing since it clearly is supports in Swagger.

**Comment by tlivings** [comment]
This shouldn't be occurring anymore.
