### ISSUE TITLE
Unexpected token .

### ISSUE THREAD

**Issue by autoferrit** [krakenjs/swaggerize-hapi#81]
I freshly generate a spec from a yaml file, which has been validated and used properly elsewhere. When generating, then running the project with `npm server.js` I get the following error

```bash
❯ node server.js
/project/handlers/addresses/{address_id}.js:14
    get: function api.address.get(req, res, next) {
                     ^
SyntaxError: Unexpected token .
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/shawn/code/src/gitlab.com/forkbomb.co/forkbomb/zbudget/node_modules/swaggerize-routes/lib/readhandlers.js:30:27
```
That file in question is this:
```javascript
'use strict';
var dataProvider = require('../../data/addresses/{address_id}.js');
/**
 * Operations on /addresses/{address_id}
 */
module.exports = {
    /**
     * summary: Get a paginated list of addresses.
     * description: This can only be done by the logged in user.
     * parameters: 
     * produces: 
     * responses: 200, 401, 404
     */
    get: function api.address.get(req, res, next) {
        /**
         * Get the data for response 200
         * For response `default` status 200 is used.
         */
        var status = 200;
        var provider = dataProvider['get']['200'];
        provider(req, res, function (err, data) {
            if (err) {
                next(err);
                return;
            }
            res.status(status).send(data && data.responses);
        });
    },
    ...
}
```

It appears that the method handler singatures are different than what is in the readme, which does not reference an `api.*` object on the `get` method. It is like this for all routes generated. There is no `api` object with the given properties. in this case, no `api.address`.

**Comment by tlivings** [comment]
The method signatures will be the `operationId`. So renaming your `operationId` should fix this.
